services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    networks:
      - custom_network
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
networks:
  custom_network:
    external: true